import { readFile, writeFile } from "node:fs/promises"; import path from "node:path"; import { fileURLToPath } from "node:url";
const currentFile = fileURLToPath(import.meta.url); const currentDirectory = path.dirname(currentFile);
const usersFile = path.resolve(currentDirectory, "../data/users.json");
let usersCache = null; let cacheTimestamp = 0;
export async function loadUsers() { const now = Date.now(); if (usersCache && now - cacheTimestamp < 5000) return usersCache; try { const raw = await readFile(usersFile, "utf8"); const data = JSON.parse(raw); usersCache = data.users || []; cacheTimestamp = now; return usersCache; } catch (e) { usersCache = []; cacheTimestamp = now; return usersCache; } }
export async function getAllUsers() { return (await loadUsers()).map((u) => { const s = { ...u }; delete s.password; return s; }); }
export async function findUser(id) { const n = String(id || "").trim().toLowerCase(); if (!n) return null; return (await loadUsers()).find((u) => String(u.email || "").toLowerCase() === n || String(u.username || "").toLowerCase() === n || String(u.employeeId || "").toLowerCase() === n) || null; }
export async function verifyPassword(id, pw) { const u = await findUser(id); if (!u) return null; if (!pw || pw !== u.password) return null; const s = { ...u }; delete s.password; return s; }
async function saveUsers(users) { try { await writeFile(usersFile, JSON.stringify({ users, _updated: new Date().toISOString() }, null, 2), "utf8"); usersCache = users; cacheTimestamp = Date.now(); } catch (e) { throw new Error("Unable to save."); } }
export async function changePassword(id, cur, nw) { const n = String(id || "").trim().toLowerCase(); if (!n) throw new Error("Identifier required."); if (!cur) throw new Error("Current password required."); if (!nw) throw new Error("New password required."); if (nw.length < 8) throw new Error("Password must be at least 8 characters."); if (nw === cur) throw new Error("Must differ."); const users = await loadUsers(); const i = users.findIndex((u) => String(u.email || "").toLowerCase() === n || String(u.employeeId || "").toLowerCase() === n); if (i === -1) throw new Error("Account not found."); if (users[i].password !== cur) throw new Error("Current password is incorrect."); users[i].password = nw; await saveUsers(users); return true; }
export async function adminUpdateUser(email, updates) { const n = String(email || "").trim().toLowerCase(); if (!n) throw new Error("Email required."); const users = await loadUsers(); const i = users.findIndex((u) => String(u.email || "").toLowerCase() === n); if (i === -1) throw new Error('Account "' + email + '" not found.'); for (const [k, v] of Object.entries(updates)) { if (!["name","role","department","phone","password"].includes(k)) continue; if (k === "password") { if (!v || String(v).length < 8) throw new Error("Password too short."); users[i].password = String(v); } else { users[i][k] = String(v || "").trim() || users[i][k]; } } await saveUsers(users); const s = { ...users[i] }; delete s.password; return s; }
